#!/usr/bin/env bash

protected_dir="/home/jovyan/filers"

# Function to handle attempts to delete the protected directory itself
delete_protected_dir() {
    echo "Deleting $protected_dir directory is not allowed."
    echo "Aborting."
    exit 1
}

# Function to prompt for confirmation when using rm -r or rm -rf
confirm_delete() {
    local target="$1"
    local recursive_mode="$2"
    read -p "You are about to recursively delete files in $target. Are you sure? (y/n): " confirm
    case $confirm in
        [yY])
            /bin/rm "$recursive_mode" "$target"  # Use the appropriate recursive mode
            ;;
        [nN])
            echo "Deletion cancelled for directory $target"
            ;;
        *)
            echo "Invalid input. Deletion cancelled for directory $target"
            ;;
    esac
}

# Main script
if [[ "$1" == "-r" || "$1" == "-rf" ]]; then
    recursive_mode="$1"
    shift  # Remove the recursive flag from arguments

    for arg in "$@"; do
        if [[ $(realpath "$arg") == $(realpath "$protected_dir") ]]; then
            delete_protected_dir
        fi
    done

    for arg in "$@"; do
        if [[ -d "$arg" ]]; then
            if [[ $(realpath "$arg") == $(realpath "$protected_dir")* ]]; then
                confirm_delete "$arg" "$recursive_mode"
            else
                /bin/rm "$recursive_mode" "$arg"
            fi
        else
            /bin/rm "$recursive_mode" "$arg"
        fi
    done
else
    /bin/rm "$@"
fi
