# Security hardening
www-frame-origin=none
www-enable-origin-check=1
www-same-site=lax
auth-timeout-minutes=10080

# Library path fix (https://github.com/rstudio/rstudio/issues/14060)
rsession-ld-library-path=/opt/conda/lib
