#!/usr/bin/env python3
"""
Set MinIO Client aliases for each filer share.
"""

import argparse
from filers_common import init_all_filers


def main():
    "Invoked when running filer-mc-init from command line."

    cmd_parser = argparse.ArgumentParser(
        description="Set MinIO Client aliases for each filer share."
    )
    cmd_parser.add_argument(
        "-q",
        "--quiet",
        help="suppress printing of output",
        action="store_true",
    )
    cmd_parser.add_argument(
        "--indicate-init-done-file",
        help=(
            "file that indicates initialization command as been executed, "
            "default /tmp/_filer_minio_client_init.done"
        ),
        default="/tmp/_filer_minio_client_init.done",
    )
    args = cmd_parser.parse_args()

    init_all_filers(
        debug_print=not args.quiet,
        indicate_done_file=args.indicate_init_done_file,
    )


if __name__ == "__main__":
    main()
