name: Auto-label PRs ready for beta
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    #if: github.event.review.state == 'approved' && ${{ github.event.pull_request.base.ref }} == "beta" 
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved. Adding label for beta"

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: "ready for beta"
      