name: Promote Beta to Master
on:
  schedule:
    # Every wednesdays, at 2h30/3h30 am(EST/EDT)
    # running after the beta-auto-merge workflow to avoid overlap
    - cron: "30 7 * * WED"

jobs:
  get-bi-weekly-schedule:
    runs-on: ubuntu-latest
    outputs:
      biweekly: ${{ steps.get-biweekly-modulo.outputs.biweekly }}
    steps:
      # Step to determine the week number in the year, to run this job bi-weekly
      # cron schedule doesn't support "every 2 weeks" scenarios.
      # runs on alternating weeks from the beta-auto-merge.yaml workflow
      - name: Get bi-weekly week number value
        id: get-biweekly-modulo
        run: |
          numWeek=$(date +%U)
          echo "biweekly=$((numWeek % 2))" >> $GITHUB_OUTPUT
          echo "This is week #$numWeek, biweekly modulo is at $((numWeek % 2))."
          echo "Job will run on value==0"
          
  create-pr-beta-to-master:
    runs-on: ubuntu-latest
    needs: get-bi-weekly-schedule
    if: ${{ needs.get-bi-weekly-schedule.outputs.biweekly == 0 }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:    
    - name: "Checkout beta"
      uses: actions/checkout@v4
      with:
        ref: beta
    
    - name: Create PR for beta to master
      run: |
        gh pr create --base master --title "chore: promote beta to master" \
          --body "Automatically generated PR to merge beta to master" \
          --label auto-deploy

