name: Promote Beta to Master
on:
  schedule:
    # Every wednesdays, at 2/3 am(EST/EDT)
    - cron: "0 7 * * WED"
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

jobs:
  get-bi-weekly-schedule:
    runs-on: ubuntu-latest
    outputs:
      biweekly: ${{ steps.get-biweekly-modulo.outputs.biweekly }}
    steps:
      # Step to determine the week number in the month, to run this job bi-weekly
      # cron schedule doesn't support "every 2 weeks" scenarios.
      # runs on alternating weeks from the beta-auto-merge.yaml workflow
      - name: Get bi-weekly week number value
        id: get-biweekly-modulo
        run: |
          numWeek=$((($(date +%-d)-1)/7+1))
          echo "biweekly=$((numWeek % 2))" >> $GITHUB_OUTPUT
          echo "Biweekly modulo is at $((numWeek % 2)). Job will run on value==1"

  get-auto-merge-beta-prs:
    runs-on: ubuntu-latest
    needs: get-bi-weekly-schedule
    if: ${{ needs.get-bi-weekly-schedule.outputs.biweekly == 1 }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:    
    - name: "Checkout master"
      uses: actions/checkout@v4
      with:
        ref: beta-clone-for-testing
        # ref: master
    
    - name: "Merge Beta to Master"
      #run: git merge beta
      run: git merge test-beta-clean

    - name: "Push updated master to remove"
      run: |
        if [ -z "$(git status --short)" ]; then
          echo "Clean working tree. Pushing master"
          git push
        else
          echo "Dirty working tree. Not pushing to master"
        fi