name: Merge to Beta
on:
  schedule:
    # Every wednesdays, at 2/3 am(EST/EDT)
    - cron: "0 7 * * WED"

jobs:
  get-auto-merge-beta-prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    # Step to determine the week number in the month, to run this job bi-weekly
    # cron schedule doesn't support "every 2 weeks" scenarios.
    # runs on alternating weeks from the beta-auto-merge.yaml workflow
    - name: Get bi-weekly week number value
      run: |
        numWeek=$((($(date +%-d)-1)/7+1))
        echo "BIWEEKLY=$((numWeek % 2))" >> $GITHUB_ENV
        echo "Biweekly modulo is at $((numWeek % 2)). Job will run on value==1"
    
    - uses: actions/checkout@v4
      if: env.BIWEEKLY == 1

    - name: "Merge ready for beta PRs"
      if: env.BIWEEKLY == 1
      run: |
        if [ -z "$(git status --short)" ]; then
          echo "Clean"
        else
          echo "Dirty"
        fi