name: Nightly test
on:
  schedule:
    # Execute at 2am EST every day
    - cron:  '0 7 * * *'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY_NAME: "k8scc01covidacr.azurecr.io"
      tag: "v2"
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: echo "Environment has been set up."

  jupyterlab-cpu-test:
    needs: [vars]
    uses: ./.github/workflows/docker-pull-test.yaml
    with:
      image: "jupyterlab-cpu"
      registry-name: "${{ needs.vars.outputs.REGISTRY_NAME }}"
      tag: "${{ needs.vars.outputs.tag }}"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      CVE_ALLOWLIST: ${{ secrets.CVE_ALLOWLIST}}

  sas-test:
    needs: [vars]
    uses: ./.github/workflows/docker-pull-test.yaml
    with:
      image: "sas"
      registry-name: "${{ needs.vars.outputs.REGISTRY_NAME }}"
      tag: "${{ needs.vars.outputs.tag }}"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      CVE_ALLOWLIST: ${{ secrets.CVE_ALLOWLIST}}
