name: Nightly test
on:
  schedule:
    # Execute at 2am EST every day
    - cron:  '0 7 * * *'

env:
  REGISTRY_NAME: "k8scc01covidacr.azurecr.io"
  BRANCH_NAME: "v2"

jobs:
  nightly-tests:
    strategy:
      matrix:
        image:
          - jupyterlab-cpu
          - sas
    uses: ./.github/workflows/docker-pull-test.yaml
    with:
      image: ${{ matrix.image }}
      registry-name: "${{ env.REGISTRY_NAME }}"
      branch-name: "${{ env.BRANCH_NAME }}"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      CVE_ALLOWLIST: ${{ secrets.CVE_ALLOWLIST}}