name: Merge to Beta
on:
  pull_request:
   types:
    - opened
    - edited
    - synchronize
    - reopened
  issue_comment:
    types: [created, deleted, edited]
  
# on:
#   schedule:
#     # Execute at 2am EST every day
#     - cron:  '0 7 * * *'

jobs:
  get-auto-merge-beta-prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      prList: ${{steps.get-pr-numbers.outputs}}
    steps:
    - uses: actions/checkout@v4

    # - name: "Get ready-for-beta PRs"
    #   run: gh pr list -l "ready for beta"

    # - id: get-pr-numbers
    #   name: "Get PR numbers for ready-for-beta PRs"
    #   run: |
    #     pr_list=$(gh pr list -l "ready for beta" --json number --jq "[.[].number]")
    #     echo ${{ toJSON(pr_list) }} >> "$GITHUB_OUTPUT"

    - id: get-pr-numbers
      name: "Get PR numbers for ready-for-beta PRs"
      run: |
        pr_list=$(gh pr list -l "ready for beta" --json number --jq "[.[].number]")
        
        for i in $pr_list
        do
          echo "$i"
        done
  
  # merge-auto-merge-beta-prs:
  #   runs-on: ubuntu-latest
  #   needs: get-auto-merge-beta-prs
  #   env:
  #     GH_TOKEN: ${{ github.token }}
  #     matrix: ${{ fromJSON(needs.get-auto-merge-beta-prs.outputs.prList) }}
  #   steps:
  #   - run: echo "$matrix"