name: Merge to Beta
on:
  # schedule:
  #   # Every wednesdays, at 2/3 am(EST/EDT)
  #   - cron: "0 7 * * WED"
  # workflow_dispatch:
  pull_request:
   types:
    - opened
    - edited
    - synchronize
    - reopened
  issue_comment:
    types: [created, deleted, edited]

jobs:
  get-auto-merge-beta-prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    # Step to determine the week number in the month, to run this job bi-weekly
    # cron schedule doesn't support "every 2 weeks" scenarios.
    - name: Get bi-weekly week number value
      run: |
        numWeek=$((($(date +%-d)-1)/7+1))
        biweekly=$((numWeek % 2))
        echo "Week num is $numWeek. biweekly is $biweekly
        echo "BIWEEKLY=$biweekly" >> $GITHUB_ENV
    
    - uses: actions/checkout@v4
      if: env.BIWEEKLY == 0

    - name: "Merge ready for beta PRs"
      if: env.BIWEEKLY == 0
      run: |
        # Get list of PR numbers with label "read for beta"
        # pr_list format is "1 24 43 11"
        pr_list=$(gh pr list -l "ready for beta" --json number --jq "[.[].number] | @sh")

        for i in $pr_list
        do
            # for each PR, get their relevant info
            prInfo=$(gh pr view $i --json baseRefName,mergeStateStatus,isDraft,mergeable,title,reviewDecision)
            targetBranch=$(echo $prInfo | jq ".baseRefName")
            mergeState=$(echo $prInfo | jq ".mergeStateStatus")
            isDraft=$(echo $prInfo | jq ".isDraft")
            isMergeable=$(echo $prInfo | jq ".mergeable")
            title=$(echo $prInfo | jq ".title")
            review=$(echo $prInfo | jq ".reviewDecision")

            # if PR matches all our conditions, merge it
            if [[ "$targetBranch" == '"beta-clone-for-testing"'
                && "$mergeState" == '"CLEAN"'
                && $isDraft == false
                && $isMergeable == '"MERGEABLE"'
                && $review == '"APPROVED"' ]]; then
                
                echo "MERGING PR #$i"
                gh pr merge $i --delete-branch --squash
            else
                echo "Not merging PR #$i - $title"
                echo ""
                echo "Target branch should be "beta": is $targetBranch"
                echo "Merge state should be "CLEAN": is $mergeState"
                echo "Should not be in draft. Is draft: $isDraft"
                echo "Should be mergeable. Is mergeable: $isMergeable"
                echo "Should be reviewed. Review is: $review"
            fi
            echo "----------------------------"
        done