name: Merge to Beta
on:
  pull_request:
   types:
    - opened
    - edited
    - synchronize
    - reopened
  issue_comment:
    types: [created, deleted, edited]
  
# on:
#   schedule:
#     # Execute at 2am EST every day
#     - cron:  '0 7 * * *'

jobs:
  auto-merge-beta-prs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      REPO: ${{ github.event.repository.name }}
    steps:
      - name: "Get ready-for-beta PRs"
        run: gh pr list -l ready-for-beta --repo $REPO
